import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = sns.load_dataset('iris')
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
df.hist(figsize=(10, 8), bins=15, edgecolor='black')
plt.suptitle('Histograms of Iris Features')
plt.show()
plt.figure(figsize=(10, 6))
sns.boxplot(data=df.drop('species', axis=1))
plt.title('Boxplots of Numerical Features')
plt.show()
plt.figure(figsize=(8, 6))
sns.scatterplot(data=df, x='petal_length', y='petal_width', hue='species')
plt.title('Petal Length vs Petal Width')
plt.show()
corr_matrix = df.drop('species', axis=1).corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Heatmap of Feature Correlations')
plt.show()
from scipy.stats import zscore
z_scores = np.abs(zscore(df.drop('species', axis=1)))
outliers = (z_scores > 3).any(axis=1)
print(f"Number of outliers: {outliers.sum()}")
print("Outlier Rows:\n", df[outliers])
sns.pairplot(df, hue='species', height=2.5)
plt.suptitle('Pairplot of Iris Dataset', y=1.02)
plt.show()
